"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-08 16:48:14.653397

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Seed data lives *inside* the migration on purpose: a migration is a frozen snapshot,
# so re-running it years later gives the same result even if app code has changed.
GENRES = [
    "Action", "Adult", "Adventure", "Animation", "Biography", "Comedy", "Crime",
    "Documentary", "Drama", "Family", "Fantasy", "Film-Noir", "Game-Show", "History",
    "Horror", "Music", "Musical", "Mystery", "News", "Reality-TV", "Romance", "Sci-Fi",
    "Sport", "Talk-Show", "Thriller", "War", "Western",
]  # fmt: skip

MOODS = {
    # name: (description, genres)
    "Feel-good": ("Light, warm, leaves you smiling", ["Comedy", "Family", "Animation", "Musical"]),
    "Edge of my seat": ("Tension and suspense", ["Thriller", "Mystery", "Crime"]),
    "Mind-bending": ("Big ideas, twists, other worlds", ["Sci-Fi", "Mystery", "Fantasy"]),
    "Cry it out": ("Emotional, moving stories", ["Drama", "Romance", "Biography"]),
    "Adrenaline rush": ("Explosions, chases, battles", ["Action", "Adventure", "War", "Sport"]),
    "Spooky night": ("Scares and dread", ["Horror", "Mystery"]),
    "Learn something": ("True stories, real-world topics", ["Documentary", "History", "Biography"]),
    "Date night": ("Romantic and fun", ["Romance", "Comedy", "Musical"]),
    "Dark & gritty": ("Crime, moral grey zones, noir", ["Crime", "Film-Noir", "Thriller", "War"]),
    "Classic Western": ("Cowboys and frontier tales", ["Western"]),
}  # fmt: skip


def seed_reference_data() -> None:
    genres = sa.table("genres", sa.column("name", sa.String))
    moods = sa.table("moods", sa.column("name", sa.String), sa.column("description", sa.Text))
    op.bulk_insert(genres, [{"name": g} for g in GENRES])
    op.bulk_insert(moods, [{"name": m, "description": d} for m, (d, _) in MOODS.items()])

    # Link moods to genres by *name*, letting the DB look up the generated ids.
    conn = op.get_bind()
    for mood, (_, genre_names) in MOODS.items():
        conn.execute(
            sa.text(
                "INSERT INTO mood_genres (mood_id, genre_id) "
                "SELECT m.id, g.id FROM moods m JOIN genres g ON g.name = ANY(:genres) "
                "WHERE m.name = :mood"
            ),
            {"mood": mood, "genres": genre_names},
        )


def upgrade() -> None:
    """Upgrade schema."""
    # Extensions ship with Postgres (pgvector with our image) but must be enabled per DB.
    # pg_trgm must exist before ix_movies_title_trgm (it provides gin_trgm_ops).
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "genres",
        sa.Column("id", sa.SmallInteger(), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_genres")),
        sa.UniqueConstraint("name", name=op.f("uq_genres_name")),
    )
    op.create_table(
        "moods",
        sa.Column("id", sa.SmallInteger(), nullable=False),
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_moods")),
        sa.UniqueConstraint("name", name=op.f("uq_moods_name")),
    )
    op.create_table(
        "movies",
        sa.Column("tconst", sa.String(length=12), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("original_title", sa.Text(), nullable=True),
        sa.Column("year", sa.SmallInteger(), nullable=True),
        sa.Column("runtime_min", sa.Integer(), nullable=True),
        sa.Column("is_adult", sa.Boolean(), server_default="false", nullable=False),
        sa.PrimaryKeyConstraint("tconst", name=op.f("pk_movies")),
    )
    op.create_index(
        "ix_movies_title_trgm",
        "movies",
        ["title"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops"},
    )
    op.create_index("ix_movies_year", "movies", ["year"], unique=False)
    op.create_table(
        "mood_genres",
        sa.Column("mood_id", sa.SmallInteger(), nullable=False),
        sa.Column("genre_id", sa.SmallInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["genre_id"],
            ["genres.id"],
            name=op.f("fk_mood_genres_genre_id_genres"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["mood_id"], ["moods.id"], name=op.f("fk_mood_genres_mood_id_moods"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("mood_id", "genre_id", name=op.f("pk_mood_genres")),
    )
    op.create_table(
        "movie_genres",
        sa.Column("tconst", sa.String(length=12), nullable=False),
        sa.Column("genre_id", sa.SmallInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["genre_id"],
            ["genres.id"],
            name=op.f("fk_movie_genres_genre_id_genres"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tconst"],
            ["movies.tconst"],
            name=op.f("fk_movie_genres_tconst_movies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("tconst", "genre_id", name=op.f("pk_movie_genres")),
    )
    op.create_index("ix_movie_genres_genre_id", "movie_genres", ["genre_id"], unique=False)
    op.create_table(
        "ratings",
        sa.Column("tconst", sa.String(length=12), nullable=False),
        sa.Column("avg_rating", sa.Numeric(precision=3, scale=1), nullable=False),
        sa.Column("num_votes", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tconst"], ["movies.tconst"], name=op.f("fk_ratings_tconst_movies"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("tconst", name=op.f("pk_ratings")),
    )
    op.create_table(
        "tmdb_cache",
        sa.Column("tconst", sa.String(length=12), nullable=False),
        sa.Column("tmdb_id", sa.Integer(), nullable=True),
        sa.Column("poster_path", sa.Text(), nullable=True),
        sa.Column("overview", sa.Text(), nullable=True),
        sa.Column("cast", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "fetched_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tconst"],
            ["movies.tconst"],
            name=op.f("fk_tmdb_cache_tconst_movies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("tconst", name=op.f("pk_tmdb_cache")),
    )
    op.create_table(
        "watchlist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tconst", sa.String(length=12), nullable=False),
        sa.Column("status", sa.String(length=10), server_default="to_watch", nullable=False),
        sa.Column("priority", sa.SmallInteger(), server_default="3", nullable=False),
        sa.Column("source", sa.String(length=20), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("my_rating", sa.Numeric(precision=3, scale=1), nullable=True),
        sa.Column(
            "added_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("watched_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('to_watch', 'watched', 'dropped')", name=op.f("ck_watchlist_status_valid")
        ),
        sa.CheckConstraint("my_rating BETWEEN 0 AND 10", name=op.f("ck_watchlist_my_rating_range")),
        sa.CheckConstraint("priority BETWEEN 1 AND 5", name=op.f("ck_watchlist_priority_range")),
        sa.ForeignKeyConstraint(
            ["tconst"], ["movies.tconst"], name=op.f("fk_watchlist_tconst_movies")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_watchlist")),
        sa.UniqueConstraint("tconst", name=op.f("uq_watchlist_tconst")),
    )
    # ### end Alembic commands ###

    seed_reference_data()


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("watchlist")
    op.drop_table("tmdb_cache")
    op.drop_table("ratings")
    op.drop_index("ix_movie_genres_genre_id", table_name="movie_genres")
    op.drop_table("movie_genres")
    op.drop_table("mood_genres")
    op.drop_index("ix_movies_year", table_name="movies")
    op.drop_index(
        "ix_movies_title_trgm",
        table_name="movies",
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops"},
    )
    op.drop_table("movies")
    op.drop_table("moods")
    op.drop_table("genres")
    # ### end Alembic commands ###
    # Extensions are left installed: other objects may depend on them.
