"""index ratings num_votes

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-08 17:24:36.032425

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_ratings_num_votes", "ratings", ["num_votes"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_ratings_num_votes", table_name="ratings")
    # ### end Alembic commands ###
