"""tmdb tagline and director

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-09 11:06:46.640204

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0004"
down_revision: str | Sequence[str] | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tmdb_cache", sa.Column("tagline", sa.Text(), nullable=True))
    op.add_column("tmdb_cache", sa.Column("director", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tmdb_cache", "director")
    op.drop_column("tmdb_cache", "tagline")
    # ### end Alembic commands ###
